os: linux
dist: trusty
language: node_js
node_js:
  - "10.0.0"
addons:
  chrome: stable
before_install:
- npm i -g npm
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add -
- sudo sh -c "echo 'deb http://opensource.wandisco.com/debian/ wheezy svn17' > /etc/apt/sources.list.d/wandisco-subversion.list"
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
- npm --version
script: npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - node_modules
env:
  global:
    - MX_APP_NAME=charts102
    - MX_BRANCH_NAME=trunk
    - MX_PROJECT_ID=649a8fda-c4a6-4303-9d8e-31402bc2840e
    - MX_ENVIRONMENT=Sandbox
    - MX_USER=widgets@mendix.com
deploy:
  provider: releases
  token: $GITHUB_KEY
  file_glob: true
  file: dist/release/*
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
